### ISSUE TITLE
Pricing Page

### ISSUE THREAD

**Issue by mrgwilliam** [IllyaDesigns/CheckIn#26]
Create an Pricing page

- Reference: https://sendgrid.com/pricing

1. Add route to Frontend.php routes - link controller
2. Create controller method and return view
3. Create and successfully return view
4. Create a pull request

Here is some additional resources:
http://bootsnipp.com/search?q=pricing

Any questions reply as a comment
===

**Comment by mrgwilliam** [comment]
Please work with @ZeBuum on this issue

**Comment by ZeBuum** [comment]
Started working on the foundation, committed to branch will work on fleshing it out with Jen soon.
